; CyberJack — Default Engine Config
; Collision Channel `UIInteractable` для интерактивных коллайдеров на MetaHuman костях.

[/Script/Engine.CollisionProfile]
+DefaultChannelResponses=(Channel=ECC_GameTraceChannel1,Name="UIInteractable",DefaultResponse=ECR_Ignore,bTraceType=True,bStaticObject=False)

[/Script/Engine.Settings]
GameDefaultMap=/Game/Maps/CJ_TestMap.CJ_TestMap

[/Script/Engine.RendererSettings]
r.GenerateMeshDistanceFields=False
r.DefaultFeature.AutoExposure=False
