import React, { useState } from 'react';
import { CalibrationBiometrics, CalibrationStateTrends } from '../CalibrationBiometrics';
import './ComponentGallery.css';

const actionImage='/character-images/actions-by-point/feet/gentle_stroke_s2.png';
const actions=[
  ['Мягкое поглаживание','приятное · тактильное','1'],
  ['Массаж','доверие · расслабление','2'],
  ['Провести языком','интимное · возбуждение','3'],
  ['Кубик льда','контраст · чувствительность','4'],
];

function ActionCard({index=0,state='default',onClick}:{index?:number;state?:string;onClick?:()=>void}){
  const action=actions[index%actions.length];
  return <div className={`${state} gallery-action-wrap`} style={{'--result-pulse-duration':'2.6s'} as React.CSSProperties}>
    <button onClick={onClick} className="operation-execute-tile" style={{'--action-image':`url("${index ? ['/character-images/actions-by-point/feet/deep_massage.png','/character-images/actions-by-point/feet/licking_s3.png','/character-images/actions-by-point/feet/ice_cube_s2.png'][index-1] : actionImage}")`} as React.CSSProperties} disabled={state==='disabled'}>
      <strong>{action[0]}</strong><span className="action-intensity"><i className="active"/><i className={index>0?'active':''}/><i className={index>1?'active':''}/></span>
      <small className="action-card-tags"><span>{action[1].split(' · ')[0]}</span><span>{action[1].split(' · ')[1]}</span></small>
    </button>{state==='just-performed'&&<small className="action-completed-mark">выполнено</small>}
  </div>;
}

function ChatSample(){return <div className="character-chat gallery-chat"><header><strong>КАНАЛ КАЛИБРОВКИ</strong><span className="chat-channel-state">КАНАЛ ОТКРЫТ</span></header><div className="chat-scroll"><article className="chat-line character"><small>МИРА</small><p>Я чувствую каждое движение. Не торопись.</p></article><div className="chat-action"><span>Мягкое поглаживание · ступни</span><b>успех</b></div><article className="chat-line calibrator"><small>КАЛИБРАТОР</small><p>Скажи, если станет слишком интенсивно.</p></article><article className="chat-line system"><small>СИСТЕМА</small><p>Возбуждение +4.2 · доверие +1.1</p></article><article className="chat-line observer"><small>ИОНА</small><p>Она перестала отводить взгляд.</p></article></div><form className="speech-input"><select><option>Мира</option></select><textarea/><button>➤</button></form></div>}

function ProcessSample({active,level=2,onLevel,onStop,onStart}:{active:boolean;level?:number;onLevel?:(n:number)=>void;onStop?:()=>void;onStart?:()=>void}){return active?<article className="control-process-row selected"><header><kbd>W/S</kbd><strong>Ритмичные фрикции</strong><span>АВТО · 3 мин</span></header><div className="control-process-intensity"><span><b>{level===1?'НИЗКАЯ':level===2?'РАБОЧАЯ':'УСИЛЕННАЯ'}</b></span><div><i className="active"/><i className={level>=2?'active':''}/><i className={level>=3?'active':''}/></div></div><footer><button onClick={()=>onLevel?.(Math.max(1,level-1))}><kbd>A</kbd> слабее</button><button onClick={()=>onLevel?.(Math.min(3,level+1))}><kbd>D</kbd> сильнее</button><button onClick={onStop}><kbd>E</kbd> завершить</button></footer></article>:<button className="control-process-idle" onClick={onStart}><i>●</i><strong>Нет активных процессов</strong><small>Нажмите, чтобы запустить демонстрацию</small></button>}

function Readiness(){return <section className="intimacy-readiness-panel"><header><small>ИНТИМНАЯ ГОТОВНОСТЬ</small><strong>СМЕШАННАЯ</strong></header><div className="intimacy-readiness-metrics"><span><small>ГОТОВНОСТЬ</small><b>52%</b></span><span><small>ВОЗБУЖДЕНИЕ</small><b>68%</b></span><span><small>ДОВЕРИЕ</small><b>41%</b></span></div><p>Сохраняйте мягкий темп и подтверждайте безопасность контакта.</p><div className="intimacy-recommendations">{actions.slice(0,3).map((a,i)=><button className="control-recommendation-card" style={{'--action-image':`url("${actionImage}")`} as React.CSSProperties}><kbd>{['A','S','D'][i]}</kbd><strong>{a[0]}</strong><small>{['готовность','доверие','возбуждение'][i]} +</small></button>)}</div></section>}

function Effects(){const [effect,setEffect]=useState<'none'|'contact'|'peak'|'result'>('none');return <><div className="gallery-effect-controls"><button onClick={()=>setEffect('contact')}>Обычный отклик</button><button onClick={()=>setEffect('result')}>Результат действия</button><button onClick={()=>setEffect('peak')}>Пиковое событие</button><button onClick={()=>setEffect('none')}>Сбросить</button></div><div className="gallery-effect-stage"><img src="/character-images/calibration-v4/mira/sitting_spread/calibration_set__wrist_cuffs__subspace.png"/>{effect==='contact'&&<div className="calibration-visual-effect effect-touch result-success" key={`c-${Date.now()}`} style={{'--effect-intensity':.8,'--effect-sharpness':.7,'--effect-duration':'1800ms','--ray-rotation':'-8deg','--ray-origin-x':'48%','--ray-origin-y':'68%'} as React.CSSProperties}><i/><i/><i/><b>Ступни</b></div>}{effect==='result'&&<div className="gallery-result"><small>РЕЗУЛЬТАТ</small><b>ПРИНЯТИЕ +3.8</b><span>возбуждение +4.2 · доверие +1.1</span></div>}{effect==='peak'&&<div className="peak-event peak-event--discharge" key={`p-${Date.now()}`}><div className="peak-event__speed-lines"/><div className="peak-event__manga-burst">{Array.from({length:12},(_,i)=><i key={i}/>)}</div><div className="peak-event__impact-arcs"><i/><i/><i/><i/></div><div className="peak-event__shards">{Array.from({length:16},(_,i)=><i key={i}/>)}</div><div className="peak-event__signal"><i/><i/><i/></div><div className="peak-event__finisher peak-event__finisher--discharge"><span>LIMIT RELEASE</span><b>FINISH</b></div></div>}</div></>}

const trends=[
  {key:'attitude',label:'Принятие',value:42,displayValue:'42%',baseline:38,history:[35,37,36,39,42],tone:'mint' as const},
  {key:'openness',label:'Открытость',value:68,displayValue:'136%',baseline:50,history:[51,54,58,63,68],tone:'blue' as const},
  {key:'plasticity',label:'Пластичность',value:100,displayValue:'200%',baseline:50,history:[55,61,72,88,100],tone:'amber' as const},
  {key:'sensitivity',label:'Чувствительность',value:157,displayValue:'314%',baseline:50,history:[60,75,92,126,157],tone:'violet' as const},
];

export function ComponentGallery(){const [theme,setTheme]=useState<'industrial'|'graphite'|'paper'|'mist'>('industrial');const [mode,setMode]=useState<'impact'|'setup'>('impact');const [paused,setPaused]=useState(false);const [tool,setTool]=useState('goals');const [toast,setToast]=useState(true);const [selectedAction,setSelectedAction]=useState(1);const [performed,setPerformed]=useState<number|null>(3);const [zone,setZone]=useState('Ступни');const [process,setProcess]=useState(true);const [level,setLevel]=useState(2);return <main className="component-gallery campaign-shell" data-theme={theme}><div className="gallery-workbench calibration-workbench"><header className="gallery-header"><div><small>CYBERJACK · UI INVENTORY</small><h1>Компоненты и эффекты</h1><p>Текущая игровая реализация внутри настоящего контекста темы.</p></div><div className="gallery-header-tools"><div className="gallery-themes"><small>ТЕМА</small>{(['industrial','graphite','paper','mist'] as const).map((id,i)=><button className={theme===id?'active':''} onClick={()=>setTheme(id)}>{['Industrial','Graphite','Sage','Mist'][i]}</button>)}</div><a href="/">Вернуться в игру</a></div></header><nav className="gallery-index"><a href="#navigation">Навигация</a><a href="#actions">Действия</a><a href="#targets">Зоны</a><a href="#metrics">Показатели</a><a href="#processes">Процессы</a><a href="#rooms">Комнаты</a><a href="#chat">Чат</a><a href="#effects">Эффекты</a></nav><div className="gallery-scroll">
  <section id="navigation" className="gallery-section"><header><div><small>00</small><h2>Навигация, заголовки и базовые контролы</h2></div><p>Все состояния в текущей теме</p></header><div className="gallery-basics"><div className="operation-mode-bar"><div className="action-tabs"><button className={mode==='impact'?'active':''} onClick={()=>setMode('impact')}>Воздействия</button><button className={mode==='setup'?'active':''} onClick={()=>setMode('setup')}>Подготовка</button></div><button className="session-pause-action" onClick={()=>setPaused(v=>!v)}>{paused?'▶ Продолжить':'Ⅱ Пауза'}</button></div><div className="game-dock-tools"><button className={tool==='protocol'?'active':''} onClick={()=>setTool('protocol')}>Протокол</button><button className={tool==='goals'?'active':''} onClick={()=>setTool('goals')}>Цели</button><button disabled>Недоступно</button></div><div className="gallery-form"><label>Список<select value={zone} onChange={e=>setZone(e.target.value)}><option>Ступни</option><option>Живот</option><option>Грудь</option></select></label><label>Поле<input value={zone} onChange={e=>setZone(e.target.value)}/></label><button className="primary" onClick={()=>setToast(true)}>Основное действие</button><button onClick={()=>setMode(v=>v==='impact'?'setup':'impact')}>Вторичное</button></div>{toast&&<div className="campaign-toast gallery-toast">Операция выполнена<button onClick={()=>setToast(false)}>×</button></div>}</div></section>
  <section id="actions" className="gallery-section"><header><div><small>01</small><h2>Иллюстрированные действия</h2></div><p>Нажатие выбирает карточку; повторное нажатие выполняет</p></header><div className="gallery-action-grid">{actions.map((_,i)=><ActionCard index={i} state={i===2?'disabled':performed===i?'just-performed':selectedAction===i?'selected':'default'} onClick={()=>{if(selectedAction===i)setPerformed(i);else{setSelectedAction(i);setPerformed(null)}}}/>)}</div></section>
  <section id="targets" className="gallery-section"><header><div><small>02</small><h2>Выбор цели, зона и прогноз</h2></div><p>Компоненты палитры в их реальной вложенности</p></header><div className="gallery-targets"><div className="operation-toolbar"><div className="target-selector"><small>ЗОНА</small><button className="target-zone-card" style={{'--zone-image':`url("/character-images/actions-by-point/feet/gentle_stroke_s2.png")`} as React.CSSProperties}><span className="target-zone-card__caption"><strong>Ступни</strong><small>Карта тела →</small></span></button></div></div><div className="zone-dynamic-row operation-zone-readout"><small>ПАРАМЕТРЫ ЗОНЫ · СТУПНИ</small><span>Чувствит. <b>126%</b><i>индекс 63</i></span><span>Принятие <b>42%</b><i>настороженно</i></span></div><section className="calibration-footer-goal monitor-goal"><div className="footer-goal-picker"><small>ЦЕЛЬ</small><button className="footer-goal-current"><span>Сенсорная адаптация</span><i>▴</i></button><button className="footer-goal-settings">⚙</button></div><div className="footer-goal-conditions goal-core-conditions"><span className="met"><i>Чувствительность</i><b>126/120</b><em>✓</em></span><span><i>Принятие</i><b>42/60</b><em>·</em></span></div></section><div className="operation-last-result monitor-last-result just-updated"><header><small>ПРОГНОЗ · МЯГКОЕ ПОГЛАЖИВАНИЕ</small><b>ОЖИДАЕТСЯ</b></header><div className="monitor-reaction-readout"><span><i>Принятие</i><b>+1…+3</b></span><span><i>Возбуждение</i><b>+2…+5</b></span></div></div></div></section>
  <section id="metrics" className="gallery-section"><header><div><small>03</small><h2>Физиология и интерпретации</h2></div><p>Живые сигналы и четыре формы долгосрочных показателей</p></header><div className="gallery-metrics"><CalibrationBiometrics activation={78} activationLabel="Высокая" capacity={64} enduranceLabel="Рабочая" capacityDelta={-2.4} pulseBpm={118} pulsePeriod={.51} breathingRate={24} breathingPeriod={2.5} activationBalance={-14} activationNature="ресурс расходуется" overload={8} overloadLabel="в норме"/><CalibrationStateTrends trends={trends}/></div></section>
  <section id="processes" className="gallery-section"><header><div><small>04</small><h2>Процессы и готовность</h2></div><p>Пустое состояние запускает процесс; A/D меняют интенсивность</p></header><div className="gallery-processes"><ProcessSample active={false} onStart={()=>setProcess(true)}/><ProcessSample active={process} level={level} onLevel={setLevel} onStop={()=>setProcess(false)} onStart={()=>setProcess(true)}/><Readiness/></div></section>
  <section id="rooms" className="gallery-section"><header><div><small>05</small><h2>Комнаты, персонажи и оборудование</h2></div><p>Карточки обзорного экрана и предметы капсулы</p></header><div className="gallery-room"><article className="person-card"><img src="/character-images/portraits/mira/guarded.png"/><div><strong>Мира</strong><span>Актив · свободна</span></div><footer><button className="primary">Взаимодействовать</button><button>Досье</button><button>Переместить ▾</button></footer></article><div className="room-equipment"><article className="laboratory-module available illustrated"><div className="laboratory-module-cover" style={{backgroundImage:'url("/backgrounds/laboratory/diagnostic_table.png")'}}/><div className="laboratory-module-copy"><header><small>ГОТОВО К РАБОТЕ</small><strong>Диагностический стол</strong></header><p>Калибровка и подробная диагностика актива.</p></div><footer><button>Поместить персонажа</button></footer></article><article className="laboratory-module occupied illustrated"><div className="laboratory-module-cover" style={{backgroundImage:'url("/backgrounds/laboratory/capsule_outpaint_masked_d1.0.png")'}}/><div className="laboratory-module-copy"><header><small>СЕАНС АКТИВЕН</small><strong>Восстановительная капсула</strong></header><p>Ника · цикл восстановления</p></div><footer><button className="primary">Управление</button><button>Освободить</button></footer></article></div><div className="capsule-infusion-list gallery-drugs">{['regenerative','neurostabilizer','sensitizer','plasticity','hormonal','biomaterial'].map((drug,i)=><div><button className="operation-execute-tile" style={{'--action-image':`url("/capsule-infusions/${drug}.png")`} as React.CSSProperties}><strong>{['Regen-R','NeuroCalm','NeuroSpike','Mnemosyne-P','Eros-V','Биоматериальный состав'][i]}</strong><small className="capsule-infusion-effect"><b>ОЖИДАЕМЫЙ ЭФФЕКТ</b><span>{['Восстановление','Стабилизация','Чувствительность','Пластичность','Возбуждение','Интимное воздействие'][i]}</span></small><small className="action-card-tags"><span>{i===5?'встроенный контур':'ампул: 3'}</span></small></button></div>)}</div></div></section>
  <section id="chat" className="gallery-section"><header><div><small>06</small><h2>Диалог</h2></div><p>Персонаж · калибратор · система · наблюдатель · действие</p></header><ChatSample/></section>
  <section id="effects" className="gallery-section"><header><div><small>05</small><h2>Событийные эффекты</h2></div><p>Запускаются вручную, чтобы сравнивать без остального интерфейса</p></header><Effects/></section>
  <section id="combinations" className="gallery-section"><header><div><small>06</small><h2>Комбинация рабочего момента</h2></div><p>Карточка + процесс + изменение показателя + реплика</p></header><div className="gallery-combination"><ActionCard index={2} state="selected"/><ProcessSample active/><article className="gallery-delta"><small>ПОСЛЕДНЕЕ ИЗМЕНЕНИЕ</small><b>Возбуждение +4.2</b><span>Принятие +0.8 · ресурс −2.4</span></article><div className="chat-line character"><small>МИРА</small><p>Реакция становится слишком сильной, но я не хочу, чтобы ты останавливался.</p></div></div></section>
 </div></div></main>}
