import React, { useState } from 'react';
import './DesignConceptLab.css';

type Page = 'rooms'|'calibration'|'capsule'|'machine';
const nav:[Page,string,string][]=[['rooms','Комнаты','L'],['calibration','Калибровка','C'],['capsule','Капсула','R'],['machine','Секс-машина','M']];
const art='/character-images/calibration-v4/mira/sitting_spread/calibration_set__wrist_cuffs__subspace.png';
const portrait='/character-images/portraits/mira/guarded.png';
const actionArt=['/character-images/actions-by-point/feet/gentle_stroke_s2.png','/character-images/actions-by-point/feet/deep_massage.png','/character-images/actions-by-point/feet/licking_s3.png','/character-images/actions-by-point/feet/ice_cube_s2.png'];

function Frame({page,title,children}:{page:Page,title:string,children:React.ReactNode}){
 return <main className="ui"><header className="ui-top"><div className="brand">CYBERJACK <small>ТЕРМИНАЛ КАЛИБРАТОРА</small></div><div className="where"><small>МЕСТО</small><b>CY-17 / {title}</b></div><div className="clock"><small>01 ЯНВ 17349</small><b>23:41</b><button>Ⅱ <span>ВРЕМЯ ИДЁТ</span></button></div></header><div className="ui-body"><nav className="ui-nav"><small>РАЗДЕЛЫ</small>{nav.map(([id,label,key])=><a className={page===id?'active':''} href={`/concept/${id}`} key={id}><kbd>{key}</kbd><b>{label}</b><span>{id==='rooms'?'3 помещения':id==='calibration'?'Мира':id==='capsule'?'занята': 'готова'}</span></a>)}</nav><section className="ui-screen">{children}</section></div></main>;
}

function Title({eyebrow,title,copy,side}:{eyebrow:string,title:string,copy:string,side?:string}){return <header className="title"><div><small>{eyebrow}</small><h1>{title}</h1><p>{copy}</p></div>{side&&<b>{side}</b>}</header>}
function Card({name,meta,image=portrait,children}:{name:string,meta:string,image?:string,children?:React.ReactNode}){return <article className="person-card"><img src={image}/><div><b>{name}</b><span>{meta}</span></div>{children}</article>}
function Equipment({name,state,image}:{name:string,state:string,image:string}){return <article className="equipment-card"><img src={image}/><div><small>ОБОРУДОВАНИЕ</small><b>{name}</b><span>{state}</span></div><button>Управление</button><button>Поместить</button></article>}

function Rooms(){const [room,setRoom]=useState(0);const rooms=['Калибровочная','Камера A','Пост наблюдения'];return <Frame page="rooms" title="Лаборатория"><Title eyebrow="ЛИЧНЫЙ КОМПЛЕКС" title="Лаборатория" copy="Помещения, персонажи и установленное оборудование." side="3 / 3"/><div className="rooms-layout"><aside className="room-list"><small>ПЛАН ЛАБОРАТОРИИ</small>{rooms.map((r,i)=><button className={room===i?'active':''} onClick={()=>setRoom(i)}><i>0{i+1}</i><span><b>{r}</b><small>{i===0?'1 чел. · 2 оборуд.':i===1?'1 чел. · 1 оборуд.':'1 чел. · 0 оборуд.'}</small></span></button>)}</aside><section className="room-detail"><header><div><small>РАБОЧЕЕ ПОМЕЩЕНИЕ</small><h2>{rooms[room]}</h2><p>Основная рабочая зона комплекса. Все существующие элементы управления сохранены.</p></div><b>3/4</b></header><section><h3>Персонажи <small>01</small></h3><Card name="Мира" meta="Актив · свободна"><div className="row-actions"><button className="primary">Калибровка</button><button>Досье</button><button>Переместить ▾</button></div></Card></section><section><h3>Оборудование <small>03</small></h3><div className="equipment-grid"><Equipment name="Диагностический стол" state="готов · свободен" image="/backgrounds/laboratory/diagnostic_table.png"/><Equipment name="Восстановительная капсула" state="занята · Ника" image="/backgrounds/laboratory/capsule_outpaint_masked_d1.0.png"/><Equipment name="Секс-машина" state="готова · свободна" image="/backgrounds/laboratory/sex_machine.png"/></div></section></section></div></Frame>}

const metricNames=['Принятие','Открытость','Пластичность','Чувствительность'];
function Metrics(){return <div className="metrics">{metricNames.map((n,i)=><article><header><small>{n}</small><b>{[42,68,127,214][i]}%</b></header><svg viewBox="0 0 100 25" preserveAspectRatio="none"><polyline points="0,20 14,18 28,21 42,12 56,15 70,7 84,10 100,3"/></svg><span>{['настороженно','растёт','выше нормы','сверхреакция'][i]}</span></article>)}</div>}
function Action({i,name,reason,keyName}:{i:number,name:string,reason:string,keyName:string}){return <button className="action" style={{'--art':`url("${actionArt[i%4]}")`} as React.CSSProperties}><kbd>{keyName}</kbd><span><small>{reason}</small><b>{name}</b></span></button>}
function Chat(){return <aside className="chat"><header><b>КАНАЛ КАЛИБРОВКИ</b><span>● ОТКРЫТ</span></header><div><p><small>Мира</small>Что именно ты собираешься проверять?</p><p className="system"><small>Система</small>Защитная реакция умеренная.</p></div><form><input placeholder="Сказать Мире…"/><button>↵</button></form></aside>}

function Calibration(){return <Frame page="calibration" title="Калибровка / Мира"><div className="workbench"><section className="monitor"><header><div><small>СОСТОЯНИЕ АКТИВА</small><b>Мира · ступни</b></div><button>Выбор зоны</button></header><Metrics/><div className="conditions"><article><small>ПОЗА</small><b>Сидит, ноги разведены</b><span>Открыты 8 зон</span></article><article><small>КОНТЕКСТЫ · 2</small><b>Фиксация запястий</b><span>Добавляет опыт: контроль</span></article></div><h3>РЕКОМЕНДАЦИИ</h3><div className="recommendations">{['Мягкое касание','Массаж','Провести языком','Кубик льда'].map((n,i)=><Action i={i} name={`${n} · Ступни`} reason={['Снизить защиту','Повысить доверие','Поднять возбуждение','Добавить контраст'][i]} keyName={`${i+1}`}/>)}</div><section className="process"><header><kbd>W/S</kbd><b>Нет активных процессов</b><span>SPACE · пауза</span></header><div className="readiness"><span>ГОТОВНОСТЬ <b>52%</b></span><span>ВОЗБУЖДЕНИЕ <b>38%</b></span><span>ДОВЕРИЕ <b>42%</b></span></div><footer><Action i={0} name="Снизить напряжение" reason="Готовность" keyName="A"/><Action i={1} name="Сохранить контакт" reason="Доверие" keyName="S"/><Action i={2} name="Усилить стимул" reason="Возбуждение" keyName="D"/></footer></section></section><section className="subject"><img src={art}/><div><small>ТЕКУЩАЯ РЕАКЦИЯ</small><b>Следит за движением руки</b><span>Ожидает следующего действия</span></div></section><aside className="palette"><header><button className="active">Воздействия</button><button>Подготовка</button></header><button className="zone"><img src={actionArt[0]}/><b>Ступни</b><span>сменить зону</span></button><div>{['Касание','Массаж','Язык','Лёд','Щекотка','Давление','Тепло','Вибрация'].map((n,i)=><Action i={i} name={n} reason="ожидаемый эффект" keyName=""/>)}</div></aside><Chat/></div></Frame>}

const drugs=[['Регенеративный','Восстановление ресурса','/capsule-infusions/regenerative.png'],['Нейростабилизатор','Снижает перегрузку','/capsule-infusions/neurostabilizer.png'],['Сенсибилизатор','Повышает чувствительность','/capsule-infusions/sensitizer.png'],['Пластицирующий','Повышает пластичность','/capsule-infusions/plasticity.png'],['Гормональный','Меняет гормональный фон','/capsule-infusions/hormonal.png'],['Биоматериальный','Интимное воздействие','/capsule-infusions/biomaterial.png']];
function Capsule(){return <Frame page="capsule" title="Восстановительная капсула"><div className="device"><section className="device-subject"><header><button>← Выйти</button><div><small>ВОССТАНОВИТЕЛЬНАЯ КАПСУЛА</small><b>Ника</b></div><span>● ЦИКЛ АКТИВЕН</span></header><img src="/character-images/portraits/nika/guarded.png"/><div className="device-process"><small>ТЕКУЩИЙ ПРОЦЕСС</small><b>Глубокое восстановление</b><span>00:37 · ресурс 71%</span></div></section><aside className="infusions"><header><b>СИСТЕМА ПОДАЧИ</b><span>Медицинские составы и встроенный контур</span></header><div>{drugs.map((d,i)=><button className="drug" style={{'--art':`url("${d[2]}")`} as React.CSSProperties}><span><small>{d[1]}</small><b>{d[0]}</b></span><em>{i===5?'встроено':'ампул: 3'}</em></button>)}</div><section className="history"><header><b>ДОЛГОВРЕМЕННАЯ ДИНАМИКА</b><span>игровое время · 24 часа</span></header><svg viewBox="0 0 100 30" preserveAspectRatio="none"><polyline points="0,24 15,22 30,23 45,18 60,19 75,10 88,12 100,4"/></svg></section></aside><section className="device-metrics"><Metrics/></section><Chat/></div></Frame>}

function Machine(){return <Frame page="machine" title="Секс-машина"><div className="device"><section className="device-subject"><header><button>← Выйти</button><div><small>СЕКС-МАШИНА</small><b>Мира</b></div><span>● ГОТОВА</span></header><img src={art}/><div className="device-process"><small>АКТИВНЫЙ ПРОЦЕСС</small><b>Ритмичные фрикции</b><span>Интенсивность 2 · 01 мин</span></div></section><aside className="machine-control"><header><small>ПУЛЬТ ВОЗДЕЙСТВИЯ</small><b>Текущий режим</b></header><div className="readiness large"><span>ГОТОВНОСТЬ <b>61%</b></span><span>ВОЗБУЖДЕНИЕ <b>73%</b></span><span>ДОВЕРИЕ <b>48%</b></span></div><section className="intensity"><small>ИНТЕНСИВНОСТЬ</small><b>РАБОЧАЯ</b><div><i className="on"/><i className="on"/><i/></div><footer><button>A · слабее</button><button>D · сильнее</button><button>E · завершить</button></footer></section><h3>КОНТЕКСТНЫЕ РЕКОМЕНДАЦИИ</h3><div className="machine-actions"><Action i={0} name="Замедлить и говорить" reason="Готовность +" keyName="A"/><Action i={1} name="Сохранить ритм" reason="Доверие +" keyName="S"/><Action i={2} name="Усилить стимул" reason="Возбуждение +" keyName="D"/></div></aside><section className="device-metrics"><Metrics/></section><Chat/></div></Frame>}

export function DesignConceptLab(){const p=(location.pathname.split('/')[2]||'rooms') as Page;return p==='calibration'?<Calibration/>:p==='capsule'?<Capsule/>:p==='machine'?<Machine/>:<Rooms/>}
