import React, { useEffect, useRef, useState } from 'react';
import './CalibrationPrototype.css';
import './ProtocolControls.css';
import './CompactCalibration.css';
import './DiagnosticCase.css';

const SUBJECT='S-AV-01', SCENE='scene_lab_calibrator', ZONE='neck';
type Strength='careful'|'firm'; type Phase='diagnosis'|'preparation'|'validation'|'won'|'failed';
type Point={localSensitivity:number;localAttitude:number;familiarity?:number;baselineLocalSensitivity?:number};
type State={capacity:number;attitude:number;tension:number;anatomy?:Record<string,Point>};
type ActionDef={id:string;label:string;hint:string}; type Step={key:string;actionId:string;label:string;strength:Strength};
type Entry={step:number;action:string;text:string;metrics:string;kind?:'normal'|'system'|'success'|'failure'};

const actions:ActionDef[]=[
  {id:'feather_stroke',label:'Провести пером',hint:'Проверить поверхностный непредсказуемый контакт'},
  {id:'gentle_stroke',label:'Мягко погладить',hint:'Проверить ровный продолжительный контакт'},
  {id:'deep_massage',label:'Надавить и размять',hint:'Проверить принятие глубокого давления'},
  {id:'ice_cube',label:'Коснуться льдом',hint:'Проверить реакцию на контраст'},
  {id:'wait',label:'Дать паузу',hint:'Проверить восстановление и сохранение результата'},
];
const validationSteps:Step[]=[
  {key:'v1',actionId:'gentle_stroke',label:'I. Продолжительный мягкий контакт',strength:'careful'},
  {key:'v2',actionId:'deep_massage',label:'II. Усиленное давление',strength:'careful'},
  {key:'v3',actionId:'ice_cube',label:'III. Температурный контраст',strength:'careful'},
];
const actionById=(id:string)=>actions.find(a=>a.id===id)!;
const point=(s:State|null)=>s?.anatomy?.[ZONE]||null;
const metricLine=(r:any)=>`удовольствие ${Number(r?.pleasure||0).toFixed(1)} · дискомфорт ${Number(r?.discomfort||0).toFixed(1)} · перегрузка ${Number(r?.overload||0).toFixed(1)}`;

function observation(id:string,result:any,before:State|null,after:State){
  const p=Number(result?.pleasure||0),d=Number(result?.discomfort||0),o=Number(result?.overload||0), oldPoint=point(before),newPoint=point(after);
  if(o>12)return 'Воздействие пересекает безопасный предел: защитное напряжение сохраняется после прекращения контакта.';
  if(id==='feather_stroke')return d>p?'Защитная реакция начинается раньше выраженного физического дискомфорта: проблема связана с непредсказуемостью поверхностного контакта.':'Поверхностный контакт принят, но отклик быстро затухает — одной лёгкости недостаточно для закрепления.';
  if(id==='gentle_stroke')return p>d*1.5?'Ровный контакт воспринимается положительно. К концу воздействия шея расслабляется, но повторение будет терять новизну.':'Продолжительность контакта вызывает настороженность: принятие ещё неустойчиво.';
  if(id==='deep_massage')return newPoint&&oldPoint&&newPoint.localSensitivity<oldPoint.localSensitivity?'Давление принято, однако после него локальная чувствительность снижается. Это быстрый путь к принятию с ценой для сенсорики.':'Глубокое давление усиливает реакцию без немедленной потери чувствительности.';
  if(id==='ice_cube')return d>p?'Контраст резко усиливает отклик, но его цена — дискомфорт и быстрый рост напряжения. Использовать только после формирования принятия.':'Контраст возвращает вовлечённость и пока остаётся в положительной зоне.';
  return after.tension<(before?.tension||0)?'Пауза снижает напряжение и восстанавливает ресурс. Одновременно текущее состояние начинает возвращаться к baseline.':'Короткой паузы оказалось недостаточно для заметного восстановления.';
}

export function CalibrationPrototype(){
  const [phase,setPhase]=useState<Phase>('diagnosis'); const [strength,setStrength]=useState<Strength>('careful'); const [subject,setSubject]=useState<State|null>(null);
  const [probes,setProbes]=useState<string[]>([]); const [findings,setFindings]=useState<string[]>([]); const [entries,setEntries]=useState<Entry[]>([]);
  const [protocol,setProtocol]=useState<Step[]>([]); const [busy,setBusy]=useState(false); const [running,setRunning]=useState(false); const [error,setError]=useState<string|null>(null);
  const stepRef=useRef(0),stopRef=useRef(false),subjectRef=useRef<State|null>(null);
  const load=async()=>{const response=await fetch(`/api/state?subjectId=${SUBJECT}&sceneId=${SCENE}&pointId=${ZONE}`),data=await response.json();if(!data.success)throw new Error(data.error);subjectRef.current=data.subject;setSubject(data.subject);return data.subject as State};
  const append=(entry:Omit<Entry,'step'>)=>{stepRef.current++;setEntries(old=>[...old,{...entry,step:stepRef.current}].slice(-12));};
  const reset=async()=>{setBusy(true);setError(null);stopRef.current=true;try{await fetch('/api/subject/update',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({subjectId:SUBJECT,sensitivity:55,capacity:72,openness:58,plasticity:72,attitude:50,tension:0,baselineSensitivity:55,baselineCapacity:72,baselineOpenness:58,baselinePlasticity:72,baselineAttitude:50})});await fetch('/api/subject/point',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({subjectId:SUBJECT,pointId:ZONE,localSensitivity:54,localAttitude:46,localOpenness:48,familiarity:0,exposureCount:0,baselineLocalSensitivity:54,baselineLocalAttitude:46,baselineLocalOpenness:48})});stepRef.current=0;setPhase('diagnosis');setProbes([]);setFindings([]);setProtocol([]);setEntries([{step:0,action:'Спецификация эксперимента',text:'Подготовить шею к трём воздействиям возрастающей сложности. Каждая контрольная реакция должна остаться положительной.',metrics:'Сначала исследуйте индивидуальную реакцию актива.',kind:'system'}]);await load();}catch(e:any){setError(e.message||'Не удалось начать кейс');}finally{setBusy(false);stopRef.current=false;}};
  useEffect(()=>{reset();},[]);

  const request=async(item:Step)=>{const isWait=item.actionId==='wait';const response=await fetch(isWait?'/api/wait':'/api/tick',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(isWait?{subjectId:SUBJECT,eventId:SCENE,ticks:1,deltaTime:8,callLLM:false}:{subjectId:SUBJECT,playerId:'PL-1',sceneId:SCENE,pointId:ZONE,presetId:item.actionId,intensity:item.strength==='careful'?.65:1,skipLLM:true,skipImageGen:true})});const data=await response.json();if(!data.success)throw new Error(data.error||'Ошибка тика');return data;};
  const perform=async(item:Step,diagnostic=false)=>{const before=subjectRef.current;const data=await request(item);const after=await load();const insight=observation(item.actionId,data.tickResult,before,after);append({action:item.label,text:insight,metrics:metricLine(data.tickResult)});if(diagnostic&&item.actionId!=='wait'){setProbes(old=>{const next=old.includes(item.actionId)?old:[...old,item.actionId];if(next.length>=3)setPhase('preparation');return next});setFindings(old=>old.includes(insight)?old:[...old,insight].slice(-4));}if(after.tension>=100||after.capacity<=10){setPhase('failed');stopRef.current=true;}return{after,result:data.tickResult,insight};};
  const manual=async(action:ActionDef)=>{if(busy||phase==='validation'||phase==='won'||phase==='failed')return;setBusy(true);setError(null);try{await perform({key:crypto.randomUUID(),actionId:action.id,label:action.label,strength},phase==='diagnosis');}catch(e:any){setError(e.message);}finally{setBusy(false);}};
  const addStep=(action:ActionDef)=>{if(phase==='diagnosis')return;setProtocol(old=>[...old,{key:crypto.randomUUID(),actionId:action.id,label:action.label,strength}].slice(0,6));};
  const runProtocol=async()=>{if(!protocol.length||busy)return;setBusy(true);setRunning(true);stopRef.current=false;try{for(const item of [...protocol]){if(stopRef.current)break;const {after,result}=await perform(item);if(after.tension>=90||after.capacity<=25||Number(result.overload||0)>=30){append({action:'Протокол остановлен',text:'Защитный предел достигнут раньше завершения последовательности.',metrics:'Требуется пересмотреть порядок или добавить паузу.',kind:'failure'});break;}await new Promise(r=>setTimeout(r,350));}}catch(e:any){setError(e.message);}finally{setBusy(false);setRunning(false);}};
  const validate=async()=>{if(busy||phase!=='preparation')return;setBusy(true);setRunning(true);setPhase('validation');let passed=true;try{for(const item of validationSteps){if(stopRef.current){passed=false;break;}const {after,result}=await perform(item);const p=Number(result.pleasure||0),d=Number(result.discomfort||0),o=Number(result.overload||0),local=point(after);const ok=p>d&&o<20&&after.tension<95&&after.capacity>25&&!!local&&local.localAttitude>=52;append({action:`Оценка ${item.label}`,text:ok?'Реакция соответствует допуску.':'Реакция вышла за требования эксперимента.',metrics:ok?'Этап пройден.':'Этап провален.',kind:ok?'success':'failure'});if(!ok){passed=false;break;}await new Promise(r=>setTimeout(r,450));}setPhase(passed?'won':'failed');}catch(e:any){setError(e.message);setPhase('failed');}finally{setBusy(false);setRunning(false);}};

  const local=point(subject); const phaseLabel={diagnosis:'Диагностика',preparation:'Подготовка',validation:'Контрольная серия',won:'Допуск получен',failed:'Испытание провалено'}[phase];
  return <main className="calibration-shell diagnostic-case">
    <section className="protocol-panel"><div><p className="eyebrow">КЕЙС 01 · СЕНСОРНАЯ ПОДГОТОВКА</p><h1>Стабильная реакция шеи</h1><p>Исследуйте актив, сформируйте протокол и подготовьте его к известной контрольной серии.</p></div><div className="phase-indicator"><strong>{phaseLabel}</strong><span>{phase==='diagnosis'?`${probes.length}/3 разных проб`:phase==='preparation'?'протокол доступен':phase==='validation'?'не вмешивайтесь':phase==='won'?'серия пройдена':'нужна новая попытка'}</span></div><div className="validation-preview">{validationSteps.map((s,i)=><div key={s.key}><span>{i+1}</span><b>{s.label.replace(/^[IVX]+\. /,'')}</b></div>)}</div></section>
    <section className="observation-panel"><div className="asset-heading"><span className="asset-mark">M</span><div><p>АКТИВ · МИРА</p><h2>Наблюдения</h2></div></div><div className="telemetry"><span>Устойчивость <b>{subject?.capacity.toFixed(0)||'—'}</b></span><span>Напряжение <b>{subject?.tension.toFixed(0)||'—'}</b></span></div><h3>Рабочая гипотеза</h3>{findings.length?<ul className="findings">{findings.map((f,i)=><li key={i}>{f}</li>)}</ul>:<p className="empty-findings">Проведите разные пробы. Терминал будет фиксировать не результат вообще, а причину реакции.</p>}<div className="local-readout"><small>Телеметрия шеи</small><p>Чувствительность: {local?.localSensitivity.toFixed(1)||'—'} · принятие: {local?.localAttitude.toFixed(1)||'—'}</p></div>{error&&<div className="outcome failure">{error}</div>}</section>
    <section className="controls-panel"><div className="mode-heading"><div><h2>{phase==='diagnosis'?'Диагностические пробы':'Ручная подготовка'}</h2><p>{phase==='diagnosis'?'Нужны три разных активных воздействия. Повторы дают меньше информации.':'Уточняйте состояние вручную или добавляйте шаги в финальный протокол.'}</p></div><div className="zone-picker compact"><button className={strength==='careful'?'active':''} onClick={()=>setStrength('careful')} disabled={busy}>Осторожно</button><button className={strength==='firm'?'active':''} onClick={()=>setStrength('firm')} disabled={busy}>Уверенно</button></div></div><div className="action-grid diagnostic-actions">{actions.map(action=><div className={`action-choice ${probes.includes(action.id)?'probed':''}`} key={action.id}><button onClick={()=>manual(action)} disabled={busy||phase==='validation'||phase==='won'||phase==='failed'}><strong>{action.label}</strong><span>{action.hint}</span>{probes.includes(action.id)&&<em>изучено</em>}</button>{phase!=='diagnosis'&&<button className="queue-add" onClick={()=>addStep(action)} disabled={busy}>+ в протокол</button>}</div>)}</div></section>
    <section className="queue-panel"><h2>Финальный протокол</h2>{phase==='diagnosis'?<div className="protocol-locked"><b>Недостаточно данных</b><p>Протокол откроется после трёх разных диагностических проб.</p></div>:protocol.length?<ol>{protocol.map((item,index)=><li key={item.key}><span>{index+1}</span><div><strong>{item.label}</strong><small>{item.strength==='careful'?'осторожно':'уверенно'}</small></div><button onClick={()=>setProtocol(old=>old.filter(x=>x.key!==item.key))} disabled={busy}>×</button></li>)}</ol>:<p className="empty-queue">Составьте последовательность до шести шагов. Это ваша гипотеза о подготовке актива.</p>}{phase!=='diagnosis'&&<div className="queue-actions">{running?<button className="stop" onClick={()=>{stopRef.current=true}}>Остановить</button>:<><button onClick={()=>setProtocol([])} disabled={busy||!protocol.length}>Очистить</button><button className="run" onClick={runProtocol} disabled={busy||!protocol.length||phase!=='preparation'}>Выполнить подготовку</button></>}</div>}<div className="validation-launch"><p>Контрольная серия не редактируется. После запуска вмешательство означает провал попытки.</p><button onClick={validate} disabled={busy||phase!=='preparation'}>Начать контрольную серию</button></div>{phase==='won'&&<div className="final-result success">Эксперимент пройден. Реакция сохранила положительный знак на всех трёх этапах.</div>}{phase==='failed'&&<div className="final-result failure">Допуск не получен. Состояние можно сбросить и исследовать иначе.</div>} {(phase==='won'||phase==='failed')&&<button className="restart" onClick={reset}>Начать кейс заново</button>}</section>
    <section className="history-panel"><h2>Последние реакции</h2><ol>{[...entries].reverse().slice(0,6).map((e,i)=><li className={e.kind||'normal'} key={`${e.step}-${i}`}><span>{String(e.step).padStart(2,'0')}</span><div><strong>{e.action}</strong><small>{e.metrics}</small><p>{e.text}</p></div></li>)}</ol></section>
  </main>;
}
